export const westminsterPubs = [
  {
    id: "adam-and-eve-st-james",
    name: "Adam & Eve (St James)",
    area: "Westminster",
    postcode: "SW1H 9EX",
    address: "81 Petty France, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "albert-victoria",
    name: "Albert (Victoria)",
    area: "Westminster",
    postcode: "SW1H 0NP",
    address: "52 Victoria Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "baccarat-bar",
    name: "Baccarat Bar",
    area: "Westminster",
    postcode: "SW1X 7XL",
    address: "87-135 Brompton Road, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "bag-o-nails-victoria",
    name: "Bag O'Nails (Victoria)",
    area: "Westminster",
    postcode: "SW1W 0PP",
    address: "6 Buckingham Palace Road, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "bbar",
    name: "Bbar",
    area: "Westminster",
    postcode: "SW1W 0PP",
    address: "43 Buckingham Palace Road, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "blue-boar-pub",
    name: "Blue Boar Pub",
    area: "Westminster",
    postcode: "SW1H 9LQ",
    address: "45 Tothill Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "blue-posts",
    name: "Blue Posts",
    area: "Westminster",
    postcode: "W1D 6DJ",
    address: "28 Rupert Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "boisdale-of-belgravia",
    name: "Boisdale of Belgravia",
    area: "Westminster",
    postcode: "SW1W 9LX",
    address: "15 Eccleston Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "brewmaster",
    name: "Brewmaster",
    area: "Westminster",
    postcode: "WC2H 7AD",
    address: "37 Cranbourn Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "cask-pub-and-kitchen",
    name: "Cask Pub & Kitchen",
    area: "Westminster",
    postcode: "SW1V 2EE",
    address: "6 Charlwood Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "coach-and-horse-mayfair",
    name: "Coach & Horse (Mayfair)",
    area: "Westminster",
    postcode: "W1J 6PT",
    address: "5 Bruton Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "coach-and-horses-greek-street",
    name: "Coach & Horses",
    area: "Westminster",
    postcode: "W1D 5DH",
    address: "29 Greek Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "colonies-victoria",
    name: "Colonies (Victoria)",
    area: "Westminster",
    postcode: "SW1E 6PR",
    address: "25 Wilfred Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "crown-covent-garden",
    name: "Crown (Covent Garden)",
    area: "Westminster",
    postcode: "WC2H 9DD",
    address: "43 Monmouth Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "duke-of-york",
    name: "Duke of York",
    area: "Westminster",
    postcode: "W1S 1AF",
    address: "8 Dering Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "flight-club",
    name: "Flight Club",
    area: "Westminster",
    postcode: "SW1E 5DJ",
    address: "6 Sir Simon Milton Square, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "garrick-arms",
    name: "Garrick Arms",
    area: "Westminster",
    postcode: "WC2H 0HG",
    address: "8-10 Charing Cross Road, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "glass-blower-piccadilly",
    name: "Glass Blower (Piccadilly)",
    area: "Westminster",
    postcode: "W1B 5JY",
    address: "40-42 Glasshouse Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "gloucester",
    name: "Gloucester",
    area: "Westminster",
    postcode: "SW1X 9QR",
    address: "187 Sloane Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "golden-lion-soho",
    name: "Golden Lion (Soho)",
    area: "Westminster",
    postcode: "W1D 5BH",
    address: "51 Dean Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "grafton-arms-victoria",
    name: "Grafton Arms (Victoria)",
    area: "Westminster",
    postcode: "SW1P 2HP",
    address: "2 Strutton Ground, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "greencoat-boy-victoria",
    name: "Greencoat Boy (Victoria)",
    area: "Westminster",
    postcode: "SW1P 1PJ",
    address: "2 Greencoat Place, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "hippodrome-casino",
    name: "Hippodrome Casino",
    area: "Westminster",
    postcode: "WC2H 7JH",
    address: "Cranbourn Street, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "imperial",
    name: "Imperial",
    area: "Westminster",
    postcode: "WC2H 7BL",
    address: "5 Leicester Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "kings-arms-mayfair",
    name: "Kings Arms (Mayfair)",
    area: "Westminster",
    postcode: "W1J 7QA",
    address: "2 Shepherd Market, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "leicester-arms-piccadilly",
    name: "Leicester Arms (Piccadilly)",
    area: "Westminster",
    postcode: "W1B 5DP",
    address: "44 Glasshouse Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "liberty-london",
    name: "Liberty London",
    area: "Westminster",
    postcode: "W1B 5AH",
    address: "Regent Street, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "maple-leaf",
    name: "Maple Leaf",
    area: "Westminster",
    postcode: "WC2E 7LJ",
    address: "41 Maiden Lane, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "market-halls-victoria",
    name: "Market Halls, Victoria",
    area: "Westminster",
    postcode: "SW1E 5NE",
    address: "191 Victoria Street, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "masons-arms-mayfair",
    name: "Masons Arms (Mayfair)",
    area: "Westminster",
    postcode: "W1S 1PY",
    address: "38 Maddox Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "old-star-westminster",
    name: "Old Star (Westminster)",
    area: "Westminster",
    postcode: "SW1H 0DB",
    address: "66 Broadway, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "paxtons-head",
    name: "Paxtons Head",
    area: "Westminster",
    postcode: "SW1X 7PA",
    address: "153 Knightsbridge, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "plumbers-arms-belgravia",
    name: "Plumbers Arms (Belgravia)",
    area: "Westminster",
    postcode: "SW1W 0LN",
    address: "14 Lower Belgrave Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "prince-of-wales-covent-garden",
    name: "Prince of Wales (Covent Garden)",
    area: "Westminster",
    postcode: "WC2B 5TB",
    address: "150-151 Drury Lane, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "punch-and-judy",
    name: "Punch & Judy",
    area: "Westminster",
    postcode: "WC2E 8RF",
    address: "40 The Market, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "rose-and-crown-mayfair",
    name: "Rose & Crown (Mayfair)",
    area: "Westminster",
    postcode: "W1K 1QN",
    address: "2 Old Park Lane, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "round-table",
    name: "Round Table",
    area: "Westminster",
    postcode: "WC2N 4AL",
    address: "26-27 St Martin's Court, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "salisbury",
    name: "Salisbury",
    area: "Westminster",
    postcode: "WC2N 4AP",
    address: "90 St Martin’s Lane, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "shakespeare-victoria",
    name: "Shakespeare (Victoria)",
    area: "Westminster",
    postcode: "SW1W 0RP",
    address: "99 Buckingham Palace Road, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "shakespeares-head-soho",
    name: "Shakespeares Head (Soho)",
    area: "Westminster",
    postcode: "W1F 7HZ",
    address: "29 Great Marlborough Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "sherlock-holmes",
    name: "Sherlock Holmes",
    area: "Westminster",
    postcode: "WC2N 5DB",
    address: "10 Northumberland Street, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "silver-cross",
    name: "Silver Cross",
    area: "Westminster",
    postcode: "SW1A 2BX",
    address: "33 Whitehall, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "tattersalls-tavern",
    name: "Tattersalls Tavern",
    area: "Westminster",
    postcode: "SW1X 7QA",
    address: "1 Knightsbridge Green, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-admiralty",
    name: "The Admiralty",
    area: "Westminster",
    postcode: "WC2N 5DS",
    address: "66 Trafalgar Square, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-alfred-tennyson",
    name: "The Alfred Tennyson",
    area: "Westminster",
    postcode: "SW1X 8LA",
    address: "10 Motcomb Street, London",
    lat: null,
    lng: null,
    tags: ["gastropub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-audley",
    name: "The Audley",
    area: "Westminster",
    postcode: "W1K 2RX",
    address: "41-43 Mount Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-botanist",
    name: "The Botanist",
    area: "Westminster",
    postcode: "SW1W 8EE",
    address: "7 Sloane Square, London",
    lat: null,
    lng: null,
    tags: ["bar"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-chequers-tavern",
    name: "The Chequers Tavern",
    area: "Westminster",
    postcode: "SW1Y 6DB",
    address: "16 Duke Street, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-chesterfield-arms",
    name: "The Chesterfield Arms",
    area: "Westminster",
    postcode: "W1J 7SS",
    address: "50 Hertford Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-clarence",
    name: "The Clarence",
    area: "Westminster",
    postcode: "SW1A 2HP",
    address: "53 Whitehall, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-coach-and-horses-soho",
    name: "The Coach & Horses",
    area: "Westminster",
    postcode: "W1D 5DH",
    address: "29 Greek Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-coal-hole",
    name: "The Coal Hole",
    area: "Westminster",
    postcode: "WC2R 0DW",
    address: "91-92 Strand, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-crown-and-two-chairmen",
    name: "The Crown & Two Chairmen",
    area: "Westminster",
    postcode: "W1D 3SB",
    address: "31-32 Dean Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-devonshire",
    name: "The Devonshire",
    area: "Westminster",
    postcode: "W1D 7HW",
    address: "17 Denman Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-dog-and-duck",
    name: "The Dog & Duck",
    area: "Westminster",
    postcode: "W1D 3AJ",
    address: "18 Bateman Street, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-duke-of-argyll",
    name: "The Duke of Argyll",
    area: "Westminster",
    postcode: "W1D 7LQ",
    address: "26 Great Windmill Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-feathers",
    name: "The Feathers",
    area: "Westminster",
    postcode: "SW1H 0BH",
    address: "18-20 Broadway, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-footman",
    name: "The Footman",
    area: "Westminster",
    postcode: "W1J 5DF",
    address: "5 Charles Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-glasshouse-stores",
    name: "The Glasshouse Stores",
    area: "Westminster",
    postcode: "W1F 9UJ",
    address: "55 Brewer Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-goat-tavern",
    name: "The Goat Tavern",
    area: "Westminster",
    postcode: "W1S 4RP",
    address: "3 Stafford Street, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-grenadier",
    name: "The Grenadier",
    area: "Westminster",
    postcode: "SW1X 7NR",
    address: "18 Wilton Row, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-horse-and-groom",
    name: "The Horse & Groom",
    area: "Westminster",
    postcode: "SW1X 7BA",
    address: "7 Groom Place, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-kings-arms-buckingham-palace-road",
    name: "The Kings Arms",
    area: "Westminster",
    postcode: "SW1W 0QJ",
    address: "77 Buckingham Palace Road, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-kings-head-stafford-street",
    name: "The Kings Head",
    area: "Westminster",
    postcode: "W1S 4RX",
    address: "10 Stafford Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-lemon-tree",
    name: "The Lemon Tree",
    area: "Westminster",
    postcode: "WC2N 4BP",
    address: "4 Bedfordbury, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-lyceum-tavern",
    name: "The Lyceum Tavern",
    area: "Westminster",
    postcode: "WC2R 0HS",
    address: "354 Strand, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-lyric",
    name: "The Lyric",
    area: "Westminster",
    postcode: "W1D 7LU",
    address: "37 Great Windmill Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-market-tavern",
    name: "The Market Tavern",
    area: "Westminster",
    postcode: "W1J 7HR",
    address: "7 Shepherd Street, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-montagu-pyke",
    name: "The Montagu Pyke",
    area: "Westminster",
    postcode: "WC2H 0BP",
    address: "105-107 Charing Cross Road, London",
    lat: null,
    lng: null,
    tags: ["wetherspoons", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-nags-head",
    name: "The Nags Head",
    area: "Westminster",
    postcode: "WC2E 8BT",
    address: "10 James Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-nellie-dean",
    name: "The Nellie Dean",
    area: "Westminster",
    postcode: "W1D 3SU",
    address: "89 Dean Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-phoenix",
    name: "The Phoenix",
    area: "Westminster",
    postcode: "SW1E 5JA",
    address: "39 Wilton Road, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-punchbowl",
    name: "The Punchbowl",
    area: "Westminster",
    postcode: "W1J 5RP",
    address: "41 Farm Street, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-queens-arms",
    name: "The Queens Arms",
    area: "Westminster",
    postcode: "SW1V 1QT",
    address: "11 Warwick Way, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-queens-head-soho",
    name: "The Queen’s Head",
    area: "Westminster",
    postcode: "W1D 7HN",
    address: "Denman Street area, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-rose-and-crown-sloane",
    name: "The Rose & Crown",
    area: "Westminster",
    postcode: "SW1W 8BU",
    address: "90-92 Lower Sloane Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-royal-george",
    name: "The Royal George",
    area: "Westminster",
    postcode: "WC2H 0EA",
    address: "Charing Cross Road area, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-savoy-tap",
    name: "The Savoy Tap",
    area: "Westminster",
    postcode: "WC2R 0BA",
    address: "2 Savoy Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-ship-soho",
    name: "The Ship",
    area: "Westminster",
    postcode: "W1F 0TT",
    address: "116 Wardour Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-st-georges-tavern",
    name: "The St George's Tavern",
    area: "Westminster",
    postcode: "SW1V 1QD",
    address: "14 Belgrave Road, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-star-tavern",
    name: "The Star Tavern",
    area: "Westminster",
    postcode: "SW1X 8HT",
    address: "6 Belgrave Mews West, London",
    lat: null,
    lng: null,
    tags: ["historic", "tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-thomas-cubitt",
    name: "The Thomas Cubitt Pub Belgravia",
    area: "Westminster",
    postcode: "SW1W 9PA",
    address: "44 Elizabeth Street, London",
    lat: null,
    lng: null,
    tags: ["gastropub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-toucan",
    name: "The Toucan",
    area: "Westminster",
    postcode: "W1D 3BY",
    address: "19 Carlisle Street, London",
    lat: null,
    lng: null,
    tags: ["irish", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-willow-walk",
    name: "The Willow Walk",
    area: "Westminster",
    postcode: "SW1V 1LW",
    address: "25 Wilton Road, London",
    lat: null,
    lng: null,
    tags: ["wetherspoons", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-wilton-arms",
    name: "The Wilton Arms",
    area: "Westminster",
    postcode: "SW1X 8ED",
    address: "71 Kinnerton Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "the-windmill-mayfair",
    name: "The Windmill",
    area: "Westminster",
    postcode: "W1S 2AZ",
    address: "6-8 Mill Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "three-crowns-piccadilly",
    name: "Three Crowns (Picaddilly)",
    area: "Westminster",
    postcode: "SW1Y 6HD",
    address: "19 Babmaes Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "travellers-tavern-belgravia",
    name: "Travellers Tavern (Belgravia)",
    area: "Westminster",
    postcode: "SW1W 9RB",
    address: "4 Elizabeth Street, London",
    lat: null,
    lng: null,
    tags: ["tavern"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "two-brewers-covent-garden",
    name: "Two Brewers",
    area: "Westminster",
    postcode: "WC2H 9EP",
    address: "40 Monmouth Street, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "two-chairmen",
    name: "Two Chairmen",
    area: "Westminster",
    postcode: "SW1H 9BP",
    address: "39 Dartmouth Street, London",
    lat: null,
    lng: null,
    tags: ["historic", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "wetherspoons-victoria-station",
    name: "Wetherspoons (Victoria Station) - JD Wetherspoon",
    area: "Westminster",
    postcode: "SW1V 1JT",
    address: "Unit 5, Victoria Island, Victoria Station, London",
    lat: null,
    lng: null,
    tags: ["wetherspoons", "pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  },
  {
    id: "white-swan-covent-garden",
    name: "White Swan",
    area: "Westminster",
    postcode: "WC2N 4LF",
    address: "14 New Row, London",
    lat: null,
    lng: null,
    tags: ["pub"],
    rarity: "common",
    coverageZone: "westminster",
    active: true
  }
];
